import fs from 'node:fs';
import {forms} from '../supabase/functions/podwash-forms/schema.mjs';
const site='https://www.podwashjamaica.com';
const out='dist';fs.mkdirSync(out,{recursive:true});
for(const file of ['podwash-jamaica-logo.png','site.css','site.js'])fs.copyFileSync(`static/${file}`,`${out}/${file}`);
fs.copyFileSync('supabase/functions/podwash-forms/schema.mjs',`${out}/schema.mjs`);
const config={url:process.env.NEXT_PUBLIC_SUPABASE_URL||'https://aabqjokzpjadmpdoyhfe.supabase.co',anonKey:process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY||''};
fs.writeFileSync(`${out}/config.js`,`window.PODWASH_CONFIG=${JSON.stringify(config)};`);
const nav=[['home','Home'],['corporate','Corporate Partnerships'],['podpro','Become a PodPro'],['area','Bring PodWash to Your Area'],['about','About'],['contact','Contact']];
const links=nav.map(([id,label])=>`<a href="/#${id}">${label}</a>`).join('');
const logo='<img src="/podwash-jamaica-logo.png" alt="PodWash Jamaica — powered by EcoWash Global" width="220" height="74">';
const header=`<a class="skip" href="#main">Skip to content</a><header class="header"><div class="nav-shell"><a class="logo" href="/#home" aria-label="PodWash Jamaica home">${logo}</a><nav class="desktop-nav" aria-label="Main navigation">${links}</nav><details class="mobile-nav"><summary>Menu <span aria-hidden="true">☰</span></summary><nav aria-label="Mobile navigation">${links}</nav></details></div></header>`;
const footer=`<footer><div class="shell footer-grid"><div><a class="footer-logo" href="/#home">${logo}</a><p>Cleaner vehicles. Practical skills.<br>More possibilities for Jamaica.</p></div><nav aria-label="Footer navigation">${links}</nav><div><p class="eyebrow">Let’s connect</p><a href="mailto:autismfamilyconsultantslimited@gmail.com">Email the PodWash team ↗</a><p class="social-note">Social channels coming soon</p><div class="socials" aria-label="Social accounts are not available yet"><span aria-label="Instagram, coming soon">◎</span><span aria-label="Facebook, coming soon">f</span><span aria-label="LinkedIn, coming soon">in</span></div></div></div><div class="shell footer-bottom"><span>© ${new Date().getFullYear()} PodWash Jamaica</span><div><a href="/privacy">Privacy policy</a><a href="/terms">Terms</a><a href="/#home">Back to top ↑</a></div></div></footer>`;
const page=(title,body,path='/',robots='index,follow')=>`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${title} | PodWash Jamaica</title><meta name="description" content="Eco-friendly vehicle cleaning and practical employment pathways in Jamaica. Explore corporate partnerships, become a PodPro, or suggest a location."><meta name="robots" content="${robots}"><link rel="canonical" href="${site}${path}"><meta property="og:title" content="${title} | PodWash Jamaica"><meta property="og:type" content="website"><meta property="og:url" content="${site}${path}"><meta property="og:image" content="${site}/podwash-jamaica-logo.png"><link rel="icon" href="/podwash-jamaica-logo.png"><link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=Nunito:wght@400;500;600;700;800&family=Playfair+Display:wght@600;700&display=swap" rel="stylesheet"><link rel="stylesheet" href="/site.css"></head><body>${header}${body}${footer}<script src="/config.js"></script><script type="module" src="/site.js"></script></body></html>`;
const btn=(href,label,secondary=false)=>`<a class="button${secondary?' secondary':''}" href="${href}">${label}<span aria-hidden="true">↗</span></a>`;
const car=`<svg viewBox="0 0 600 400" role="img" aria-label="A vehicle at a PodWash cleaning station"><ellipse cx="300" cy="328" rx="240" ry="21" fill="#123a27" opacity=".1"/><path d="M90 278v-65l66-26 38-77h192l54 77 56 22v69Z" fill="#fffdf3" stroke="#132c20" stroke-width="5" stroke-linejoin="round"/><path d="m192 126-27 61h244l-40-61Z" fill="#b5d1ba" stroke="#132c20" stroke-width="4"/><path d="M281 129v57M103 222h59m250 0h63" stroke="#132c20" stroke-width="5"/><rect x="218" y="234" width="128" height="29" rx="5" fill="#efd443"/><circle cx="161" cy="279" r="37" fill="#132c20"/><circle cx="423" cy="279" r="37" fill="#132c20"/><circle cx="161" cy="279" r="16" fill="#fffdf3"/><circle cx="423" cy="279" r="16" fill="#fffdf3"/><path d="M460 134c45-3 42-57 64-57v-38" stroke="#132c20" stroke-width="6" fill="none"/><path d="M509 33h34v39h-34z" fill="#efd443" stroke="#132c20" stroke-width="4"/><g stroke="#397e45" stroke-width="4" stroke-linecap="round"><path d="m444 116-8-12m30 0-3-14m-34 44-12-3M88 111v26m-13-13h26M392 51v22m-11-11h22"/></g></svg>`;
const home=`<main id="main"><section id="home" class="hero"><div class="shell hero-grid"><div class="hero-copy"><p class="eyebrow"><span class="dot"></span> Care for your vehicles. Invest in people.</p><h1>A cleaner car.<br>A brighter <em>next chapter.</em></h1><p class="lede">PodWash Jamaica brings eco-friendly vehicle cleaning together with practical training and meaningful work opportunities for neurodivergent young adults.</p><div class="actions">${btn('#corporate','Explore corporate partnerships')}${btn('/forms/podpro','Become a PodPro',true)}</div><p class="small-note">Building partnerships and welcoming expressions of interest.</p></div><div class="hero-art"><div class="art-top"><span>PODWASH JAMAICA</span><span>Powered by EcoWash Global</span></div>${car}<div class="art-bottom"><span>Vehicle care</span><span>People first</span><span>Local opportunity</span></div><div class="art-stamp">A little care.<br>A lot of possibility.</div></div></div></section>
<div class="values-strip"><div class="shell"><span>Thoughtful vehicle care</span><span>Hands-on skills</span><span>Meaningful participation</span><span>Rooted in Jamaica</span></div></div>
<section id="corporate" class="section"><div class="shell"><div class="section-top"><p class="eyebrow">01 / Corporate partnerships</p><span>Good for your vehicles. Good for your community.</span></div><div class="split"><div><h2>Put your parking space<br>to <em>good use.</em></h2><p class="lede">Make vehicle care part of your organization’s routine — and help create opportunities for people to learn, contribute, and grow.</p>${btn('/forms/corporate','Discuss your vehicle cleaning needs')}</div><div class="copy"><p>From company fleets and employee vehicles to customer cars and vehicle inventory, we’d like to understand what reliable cleaning would look like for your organization.</p><p>Tell us about your location, the number of vehicles, and your preferred schedule. Together, we can explore an on-site partnership that fits your needs.</p><div class="mini-grid"><div><span class="icon">↻</span><h3>A routine that fits</h3><p>Discuss frequency, timing, and your site’s needs.</p></div><div><span class="icon">◇</span><h3>Purpose in practice</h3><p>Support real work experience and skill building.</p></div></div></div></div><div class="section-callout"><span>A fleet, a workplace, or a new idea? Let’s talk.</span><a href="/forms/corporate">Start a corporate partnership conversation ↗</a></div></div></section>
<section id="podpro" class="section sage"><div class="shell"><div class="section-top"><p class="eyebrow">02 / Become a PodPro</p><span>Your potential has a place here.</span></div><div class="split"><div><h2>Learn by doing.<br>Grow by <em>belonging.</em></h2><p class="lede">A PodPro is part of the PodWash team: learning practical vehicle care skills while building confidence, routines, and workplace experience.</p>${btn('/forms/podpro','Become a PodPro')}</div><div class="steps"><article><span>01</span><div><h3>Tell us about you</h3><p>Share your interests, availability, and what you would like to learn.</p></div></article><article><span>02</span><div><h3>Start a conversation</h3><p>Our team reviews your interest and discusses opportunities and support needs.</p></div></article><article><span>03</span><div><h3>Build your next step</h3><p>Explore practical experience, useful skills, and a pathway into working life.</p></div></article><p class="small-note">Submitting interest does not guarantee a position. We’ll contact you about next steps and available opportunities.</p></div></div></div></section>
<section id="area" class="section"><div class="shell area-panel"><div><p class="eyebrow">03 / Bring PodWash to your area</p><h2>Big possibilities.<br><em>Local beginnings.</em></h2><p class="lede">Know a community, business, or location where PodWash could make a difference? We’d love to hear about it.</p>${btn('/forms/area','Bring PodWash to my area')}</div><div class="area-note"><span class="compass" aria-hidden="true">↗</span><h3>Where should we grow next?</h3><p>Your local knowledge can help us find promising partnerships and places to explore — in Jamaica and beyond.</p><div class="tags"><span>Communities</span><span>Businesses</span><span>Local organizations</span></div></div></div></section>
<section id="about" class="section about"><div class="shell"><div class="section-top"><p class="eyebrow">04 / About PodWash Jamaica</p><span>Practical work. Shared purpose.</span></div><div class="split"><div><h2>Cleaner vehicles.<br><em>Stronger possibilities.</em></h2><p class="signature">AFC <span>&amp;</span> PodWash Jamaica</p></div><div class="copy"><p>Autism Family Consultants is developing a workforce initiative for autistic and otherwise neurodivergent young adults in Jamaica.</p><p>Through a micro-franchise secured with EcoWash Global, PodWash Jamaica is creating an eco-friendly setting for workforce training, skill building, and sustainable employment.</p><p>Our aim is a practical bridge from school to adulthood: building confidence, independence, and community participation through real-world experience.</p><div class="external-links"><a href="https://autismfamilyconsultants.com" target="_blank" rel="noopener">Visit Autism Family Consultants ↗</a><a href="https://ecowashglobal.com/" target="_blank" rel="noopener">Learn more about EcoWash Global ↗</a></div></div></div></div></section>
<section id="contact" class="section yellow"><div class="shell contact-grid"><div><p class="eyebrow">05 / Contact</p><h2>Good things start<br>with a <em>conversation.</em></h2><p class="lede">Have a question or an idea? Send a message to the PodWash Jamaica team.</p><p class="small-note">For detailed partnership, PodPro, or location inquiries, use the dedicated forms above.</p></div><div class="form-card" data-form="contact"></div></div></section></main>`;
fs.writeFileSync(`${out}/index.html`,page('Eco-friendly vehicle care. Meaningful opportunity.',home));
fs.mkdirSync(`${out}/forms`,{recursive:true});
for(const key of ['corporate','podpro','area']){const f=forms[key];fs.writeFileSync(`${out}/forms/${key}.html`,page(f.title,`<main id="main" class="form-page shell"><a class="back-link" href="/#${key}">← Back to PodWash Jamaica</a><div class="form-layout"><aside><p class="eyebrow">${f.eyebrow}</p><h1>${f.title}</h1><p class="lede">${f.intro}</p><p class="small-note">Fields marked * are required. All other fields are marked optional.</p></aside><div class="form-card" data-form="${key}"></div></div></main>`,`/forms/${key}`));}
fs.writeFileSync(`${out}/admin.html`,page('Submission inbox',`<main id="main" class="shell admin-page"><p class="eyebrow">PodWash Jamaica / Team</p><h1>Submission inbox</h1><form id="admin-login" class="form-card"><label for="admin-key">Founder access key</label><input id="admin-key" type="password" autocomplete="current-password" required><button class="button" type="submit">Open inbox</button><p role="status" id="admin-status"></p></form><section id="inbox" hidden><div class="inbox-toolbar"><label>Form type<select id="type-filter"><option value="">All submissions</option>${Object.entries(forms).map(([k,f])=>`<option value="${k}">${f.title}</option>`).join('')}</select></label><button id="refresh" class="button secondary">Refresh</button><button id="logout" class="text-button">Sign out</button></div><p id="inbox-status" role="status"></p><div id="submission-list"></div><button id="more" class="button secondary" hidden>Load more</button></section></main>`,'/admin','noindex,nofollow'));
const legal={privacy:`<h1>Privacy policy</h1><p>PodWash Jamaica, an Autism Family Consultants initiative, collects the information you choose to provide through our inquiry and interest forms so our team can respond, review potential partnerships and opportunities, and keep an organized record of your request.</p><h2>Information you share</h2><p>This may include contact details, organization and location information, work interests and availability, and any optional support information you provide. Applicants under 18 are asked for parent or guardian contact information. Please share only information relevant to your inquiry.</p><h2>How it is handled</h2><p>Submissions are stored using Supabase and our team receives email notifications through Resend. The website is hosted by Vercel. Access to the submission inbox is restricted to authorized team members. Service providers may process data in countries outside Jamaica.</p><h2>Your choices</h2><p>To ask about your submission, correct your details, or request deletion, email <a href="mailto:autismfamilyconsultantslimited@gmail.com">autismfamilyconsultantslimited@gmail.com</a>. Optional questions can be left blank. We do not add form submissions to a marketing list.</p><h2>External sites</h2><p>Links to partner websites take you to sites with their own privacy practices. This site uses Google Fonts to display its typefaces.</p>`,terms:`<h1>Terms of use</h1><p>This website introduces PodWash Jamaica and lets you express interest in corporate partnerships, PodPro opportunities, and potential locations.</p><h2>Expressions of interest</h2><p>Submitting a form starts a conversation. It does not create a service contract, employment offer, franchise agreement, or guarantee of availability. Service scope, schedules, pricing, eligibility, and any agreement will be discussed directly with the team.</p><h2>Using the website</h2><p>Please provide accurate information and only submit information you are authorized to share. Do not use the forms to send spam, malicious content, or unlawful material.</p><h2>Contact</h2><p>For questions, contact <a href="mailto:autismfamilyconsultantslimited@gmail.com">autismfamilyconsultantslimited@gmail.com</a>.</p>`};
for(const [key,body] of Object.entries(legal))fs.writeFileSync(`${out}/${key}.html`,page(key==='privacy'?'Privacy policy':'Terms of use',`<main id="main" class="shell legal">${body}<a class="button secondary" href="/">Return to PodWash Jamaica</a></main>`,`/${key}`));
fs.writeFileSync(`${out}/robots.txt`,`User-agent: *\nAllow: /\nDisallow: /admin\nSitemap: ${site}/sitemap.xml\n`);
fs.writeFileSync(`${out}/sitemap.xml`,`<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">${['/','/forms/corporate','/forms/podpro','/forms/area','/privacy','/terms'].map(p=>`<url><loc>${site}${p}</loc></url>`).join('')}</urlset>`);
console.log('Built PodWash landing page, forms, inbox, and policies.');
