export const icon=name=>`<i class="bi bi-${name}" aria-hidden="true"></i>`;
const button=(url,label,secondary=false)=>`<a class="button${secondary?' secondary':''}" href="${url}">${label}${icon(url.includes('corporate')?'building':url.includes('podpro')?'person-badge':'geo-alt')}</a>`;
const photo=(file,alt,cls='',eager=false)=>`<figure class="photo ${cls}"><img src="/${file}.webp" alt="${alt}" width="1536" height="1024" ${eager?'fetchpriority="high"':'loading="lazy"'}><figcaption>Illustrative imagery</figcaption></figure>`;
const benefits=[
 ['geo-alt','Convenient','PodWash brings vehicle cleaning directly to your location, reducing the need to move vehicles off site for routine cleaning.'],
 ['droplet','Environmentally conscious','Powered by EcoWash Global technology, PodWash uses approximately 2 litres of water per vehicle, significantly reducing water use compared with conventional vehicle washing methods.'],
 ['sliders','Customized','Exterior and interior cleaning services can be structured around your organization’s vehicle volume, scheduling requirements, service frequency, and operational needs.'],
 ['shield-check','Professionally supervised','PodPros work under trained PodWash supervisors who provide on-site supervision, job coaching, task support, quality oversight, and day-to-day workforce management.'],
 ['briefcase','Workforce focused','Every PodWash corporate partnership helps create paid employment and workforce development opportunities for youth and young adults.'],
 ['bullseye','Purpose built','A practical business service with a structured workforce model helps young people strengthen transferable workplace skills through actual employment.']
];
const skills=[
 ['clock','Showing Up Ready','Arriving prepared and ready to work.'],
 ['list-check','Following Instructions','Understanding directions and completing assigned tasks.'],
 ['check2-circle','Starting and Finishing Tasks','Following responsibilities from beginning through completion.'],
 ['question-circle','Asking for Help','Recognizing when assistance is needed and learning how to request it appropriately.'],
 ['chat-dots','Communication','Building effective communication with supervisors, coworkers, and others in the workplace.'],
 ['bullseye','Staying on Task','Maintaining focus and returning to a task when redirection is needed.'],
 ['chat-square-text','Receiving Feedback','Learning how to receive guidance and use it to improve performance.'],
 ['lightbulb','Problem Solving','Identifying challenges and working toward appropriate solutions.']
];
const sectors=['Auto Dealerships','Corporate and Commercial Fleets','Rental Car Companies','Airports','Business and Corporate Compounds','Shopping Centres','Residential Communities','Organizations with Vehicle Fleets or High Vehicle Traffic'];
const process=[
 ['Tell us about your needs','Share information about your organization, location, vehicles, anticipated volume, and cleaning needs.'],
 ['Site & service assessment','We assess the location and discuss vehicle volume, exterior and interior cleaning requirements, scheduling, service frequency, and operational considerations.'],
 ['Customized service plan','We develop an arrangement based on your organization’s needs, including scope of services, anticipated volume, scheduling, and service frequency.'],
 ['PodWash team deployment','Once the arrangement is established, PodWash coordinates the team, supervision, scheduling, and day-to-day delivery of services at your location.']
];
export const home=`<main id="main">
<section id="home" class="hero"><div class="shell">
 <div class="hero-bento"><div class="hero-copy"><h1>Clean Vehicles.<br>Real Jobs.<br><em>Lasting Skills.</em></h1><p>PodWash Jamaica provides environmentally conscious exterior and interior vehicle cleaning services to businesses and organizations while creating paid employment and workforce development opportunities for youth and young adults ages 16–25.</p><div class="actions">${button('#corporate','Partner with us')}${button('/forms/podpro','Become a PodPro',true)}</div></div>
 <div class="hero-visual">${photo('vehicle-care','Illustrative scene of a vehicle-care professional wiping a silver corporate vehicle at an office campus','hero-photo',true)}<div class="photo-caption"><span>Professional care.<br>Right where you need it.</span>${icon('shield-check')}</div></div></div>
 <div class="hero-summary"><div><h2>Clean vehicles are the service.<br><em>Opportunity is the impact.</em></h2></div><p>Through corporate partnerships, we provide exterior and interior vehicle cleaning at partner locations while creating opportunities for young people to earn, work, and develop transferable workplace skills through real employment.</p></div>
 <div class="water-strip"><div class="water-number">${icon('droplet')}<strong>~2<span>L</span></strong><span>of water<br>per vehicle</span></div><div><h3>A smarter way to clean vehicles.</h3><p>Powered by EcoWash Global technology, our environmentally conscious system uses significantly less water than conventional washing. Convenient vehicle cleaning where your vehicles already are.</p></div><a class="text-link" href="#corporate">Partner with us ${icon('building')}</a></div>
</div></section>
<section id="corporate" class="section corporate"><div class="shell">
 <div class="section-heading"><h2>Bring PodWash to<br><em>your organization.</em></h2><p class="lede">Convenient, environmentally conscious vehicle cleaning at your location — designed around your operation.</p></div>
 <div class="service-layout"><div class="service-copy"><h3>Vehicle cleaning designed around your operation</h3><p>Rather than routinely sending vehicles off site for cleaning, work with PodWash to develop an arrangement around your vehicle volume, location, schedule, service frequency, and cleaning needs.</p><p>Whether you manage a fleet, vehicle inventory, or a high volume of vehicles at a single location, we work with you to determine the right exterior and interior cleaning service.</p>${button('/forms/corporate','Discuss your needs')}</div><div class="sector-panel"><ul class="sector-list">${sectors.map(x=>`<li>${icon('check2')}<span>${x}</span></li>`).join('')}</ul></div></div>
 <div class="subheading"><h3>Why partner with PodWash?</h3></div><div class="benefit-grid">${benefits.map(([i,t,p])=>`<article>${icon(i)}<h3>${t}</h3><p>${p}</p></article>`).join('')}</div>
 <div class="team-panel">${photo('team-work','Illustrative scene of a supervisor and two adult coworkers reviewing a work plan beside a vehicle')}<div><h3>PodWash manages the team.</h3><p>Partnering with PodWash does not mean taking on responsibility for managing our workforce.</p><p>We manage recruitment, training, scheduling, on-site supervision, job coaching, task support, quality oversight, and day-to-day team management. Trained supervisors ensure responsibilities are understood, expectations maintained, and services completed to PodWash standards.</p><strong>Your organization partners with PodWash. PodWash manages its people.</strong></div></div>
 <div class="impact-line"><h3>A service with<br>built-in impact.</h3><div><p>Your organization receives a needed service. Young people receive an opportunity to work, earn, and grow.</p><p>Corporate partnerships create real work environments where PodPros gain paid employment, develop workplace skills, and build experience for future opportunities. The social impact is built into the business model.</p></div></div>
 <div class="process"><h3>From conversation to service.</h3><div class="process-grid">${process.map(([t,p],n)=>`<article><span class="step-number">0${n+1}</span><h4>${t}</h4><p>${p}</p></article>`).join('')}</div><div class="process-bottom"><p>Let’s talk about your organization and explore how PodWash could work within your operation.</p>${button('/forms/corporate','Let’s talk')}</div></div>
</div></section>
<section id="podpro" class="section podpro"><div class="shell">
 <div class="podpro-top"><div><h2>Build skills.<br>Gain experience.<br><em>Get paid.</em></h2><p class="lede">PodPros are the people behind PodWash Jamaica.</p><p>The PodPro Program provides youth and young adults ages 16–25 with paid work experience and skills that can transfer to future jobs, careers, and greater independence.</p><p>We welcome hardworking and reliable young people of all abilities, intentionally including autistic, ADHD, and other neurodivergent youth and young adults.</p>${button('/forms/podpro','Become a PodPro')}</div>${photo('team-work','Illustrative workplace scene showing adult team members learning together beside a vehicle','podpro-photo')}</div>
 <div class="work-pair"><article><h3>This is real work.</h3><p>PodPros work as a team providing professional vehicle cleaning to corporate partners: showing up ready, learning the job, completing responsibilities, working with others, receiving feedback, solving problems, and meeting workplace expectations.</p><p>Support is available when needed, but the experience is built around real work and real responsibilities.</p></article><article><h3>Support while you work.</h3><p>Trained PodWash supervisors provide clear instructions, on-site supervision, job coaching, feedback, task support, and guidance throughout the workday.</p><p>Support adjusts as skills and independence develop, helping PodPros learn, grow, take increasing responsibility, and experience success in a real workplace.</p></article></div>
 <div class="subheading"><div><h3>Skills that go beyond PodWash.</h3></div><p>The goal is not simply to learn how to clean vehicles.</p></div><div class="skills-grid">${skills.map(([i,t,p])=>`<article>${icon(i)}<h4>${t}</h4><p>${p}</p></article>`).join('')}</div>
 <div class="takeaway"><div><h3>Your PodWash experience can go with you.</h3><p>Communication, reliability, problem solving, task completion, teamwork, and responding to feedback matter in almost every workplace. Our goal is for PodPros to leave every work experience with more skills, more experience, and a stronger foundation for whatever comes next.</p></div><div><strong>Interested in becoming a PodPro?</strong><p>If you are 16–25 and interested in paid work experience while developing workplace skills, we would like to hear from you.</p>${button('/forms/podpro','Become a PodPro')}</div></div>
</div></section>
<section id="area" class="section"><div class="shell location-panel"><div><h2>Where should<br>PodWash go <em>next?</em></h2><p class="lede">Want to see PodWash in your community?</p><p>PodWash brings together environmentally conscious vehicle cleaning, paid employment, and workforce development. If you believe it would be a good fit for your parish, community, city, or country, we want to hear from you.</p>${button('/forms/area','Suggest a location')}</div><div class="location-aside">${icon('geo-alt')}<h3>Local knowledge.<br>New possibilities.</h3><p>Whether you are a community leader, business owner, organization, potential partner, or someone who sees a need where you live, tell us where you would like to see PodWash next.</p><div class="tags"><span>Parish</span><span>Community</span><span>City</span><span>Country</span></div></div></div></section>
<section id="about" class="section about"><div class="shell"><div class="about-grid"><div><h2>Where workforce<br>development meets<br><em>real employment.</em></h2><p class="signature">AFC <span>&amp;</span> PodWash Jamaica</p></div><div><p class="lede">An AFC Workforce Initiative connecting workforce development with actual paid employment.</p><p>Autism Family Consultants brings extensive experience supporting autistic individuals and their families in education, transition planning, workforce preparation, and preparation for adult life.</p><p>PodWash takes that experience into the workplace. Instead of only teaching young people about employment, we create opportunities for them to experience it.</p><p class="work-statement">They work. They earn. They develop skills.<br>They gain experience. They show what they can do.</p></div></div>
 <div class="about-details"><article><h3>Why PodWash?</h3><p>The transition from school and training into employment can be difficult, particularly for young people who benefit from additional opportunities to develop and demonstrate workplace skills. PodWash helps bridge that space.</p><p>Vehicle cleaning can be taught systematically, practiced repeatedly, measured clearly, and performed as a team — while providing businesses with a legitimate service they already need.</p><strong>Business and workforce development, working together.</strong></article><article><h3>An AFC Workforce Initiative</h3><p>Preparation for adulthood must extend beyond conversations about what young people may eventually do. They need opportunities to work, earn, receive feedback, solve problems, build confidence, and discover their capabilities.</p><p>Our model draws on AFC’s experience in education, transition planning, family support, and workforce preparation, moving from preparing for employment to creating opportunities for employment.</p><a class="text-link" href="https://autismfamilyconsultants.com" target="_blank" rel="noopener">Visit Autism Family Consultants ${icon('people')}</a></article></div>
 <div class="ecowash"><div>${icon('droplet')}<h3>Powered by<br>EcoWash Global.</h3></div><p>EcoWash Global vehicle cleaning technology uses approximately 2 litres of water per vehicle, allowing PodWash to combine environmental responsibility, operational convenience, and workforce opportunity within one business model.</p><a class="text-link" href="https://ecowashglobal.com/" target="_blank" rel="noopener">Explore EcoWash ${icon('globe2')}</a></div>
</div></section>
<section id="contact" class="section contact-section"><div class="shell"><div class="contact-grid"><div><h2>Let’s <em>connect.</em></h2><p class="lede">A cleaner fleet. A new opportunity.<br>A conversation worth having.</p><p>Whether your organization wants PodWash at your location, you are interested in becoming a PodPro, want to see PodWash in your area, or simply want to learn more, we would like to hear from you.</p><a class="contact-email" href="mailto:autismfamilyconsultantslimited@gmail.com">${icon('envelope')} Email the PodWash team</a><p class="small-note">For a detailed inquiry, use one of our dedicated forms below.</p></div><div class="form-card" data-form="contact"></div></div>
 <div class="closing"><h2>Clean vehicles.<br><em>Create opportunities.</em></h2><p>Environmentally conscious vehicle cleaning, real employment, and workforce development.</p><div class="closing-grid"><article><h3>For organizations</h3><p>Let’s develop a vehicle cleaning solution that works for your operation.</p><a href="#corporate">Partner with us ${icon('building')}</a></article><article><h3>For future PodPros</h3><p>Build skills. Gain experience. Get paid.</p><a href="/forms/podpro">Become a PodPro ${icon('person-badge')}</a></article><article><h3>Want PodWash in your area?</h3><p>Tell us where you would like to see PodWash next.</p><a href="/forms/area">Suggest a location ${icon('geo-alt')}</a></article></div></div>
</div></section></main>`;
